<?php
$helper = $this->helper('MagePrakash\OutofStockNotification\Helper\Data');
$products = $block->getProductCollection();
$minQty = $helper->getMinQtyMail();

?>

<table>
	<thead>
		<tr>
			<th><?=__('ID'); ?></th>
			<th><?=__('Product Name'); ?></th>
			<th><?=__('Product QTY'); ?></th>
		</tr>
	</thead>
	<tbody>
<?php
	foreach ($products as $product) {
			
			
			if($product->getTypeId()!='grouped' || $product->getTypeId()!='bundle' || $product->getTypeId()!='configurable'){
				$stockItem =  $block->getStock($product->getId());
				
				if(((int)$stockItem->getQty() <= (int)$minQty) && ((int)$stockItem->getQty() > 0)){
?>

				<tr style="text-align: center;">
					<td align="center"><?=$product->getId();?></td>
					<td align="center"><?=$product->getName();?></td>
					<td align="center"><?=$stockItem->getQty();?></td>
				</tr>
<?php
				}
			}
		
	}
?>


<?php
?>
	</tbody>
</table>