<?php// getStatus() getImage();
?>
<div>
	<div class="products wrapper list products-list">
		<form id="notify-product-list-form" method="POST">
			<input type="hidden" name="customer_id" value="<?php echo $block->getLoggedCustomerId(); ?>">
			<ol class="products list items product-items">
				<?php
					$subscribedProduct = $block->getSubscribedProductSku();
					foreach ($subscribedProduct as $key => $value) {
						$sku = $value['sku'];
					 	$product = $block->getProduct($sku);
					 	$mediaUrl = $block->getMediaUrl();
					 	$imageUrl = $mediaUrl."catalog/product".$product->getImage();
					 	$_productStock = $block->getStockItem($product->getId());
					 	?>
					 	<li class="item product product-item">
					 		<div class="product-item-info">
					 			<a class="product photo product-item-photo" href="">
					 				<img class="mageprakash-product-image-photo" src="<?php echo $imageUrl; ?>" width="240" height="300">
					 			</a>
					 			<div class="product details product-item-details">
					 				<div class="mageprakash-product-item-details">
					 					<span class="product-item-name"> <?php echo $value['name']; ?></span>
					 				</div>
					 				<div class="mageprakash-product-item-details">
					 					<span class="product-item-email"> <?php echo $value['email']; ?></span>
					 				</div>
					 				<div class="mageprakash-product-item-details">
					 					<span class="product-item-status"> <?php if ($_productStock->getIsInStock()){ echo "In Stock"; }else{ echo "Out of Stock"; } ?></span>
					 				</div>
					 				<div class="mageprakash-notify-button">
					 					<button class="action primary" formaction="<?php echo $block->getStopNotifyAction()."/sku/".$sku; ?>" type="submit" id="stop-notify">
					 						<?php 
					 						if($value['notify_status'] == 1){ echo "Stop Notify";} else{ echo "Start Notify";}?></button>
					 					<button class="action primary" type="submit" id="remove-notify" formaction="<?php echo $block->getStopRemoveAction()."/sku/".$sku; ?>">Remove</button>
					 				</div>
					 			</div>				 			
					 		</div>
					 	</li>
					 	<?php
					 } 
				?>
			</ol>
		</form>
	</div>
</div>
<style type="text/css">
	.mageprakash-product-image-photo{
		bottom: 0;
		display: block;
		left: 0;
		margin: auto;
		max-width: 100%;
		position: relative;
		right: 0;
		top: 0;
		max-width: inherit;
		height: 250px;
	}
</style>