<?php
?>
<?php $block->setPreconfiguredValue(); ?>
<?php $_product = $block->getProduct(); ?>
<?php $_associatedProducts = $block->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>
<?php $notifyBlock= $block->getLayout()->createBlock('MagePrakash\OutofStockNotification\Block\Product\Notify'); ?>

<div class="table-wrapper grouped">
    <table class="table data grouped" id="super-product-table">
        <caption class="table-caption"><?= /* @escapeNotVerified */ __('Grouped product items') ?></caption>
        <thead>
        <tr>
            <th class="col item" scope="col"><?= /* @escapeNotVerified */ __('Product Name') ?></th>
            <?php if ($_product->isSaleable()): ?>
                <th class="col qty" scope="col"><?= /* @escapeNotVerified */ __('Qty') ?></th>
            <?php endif; ?>
        </tr>
        </thead>

        <?php if ($_hasAssociatedProducts): ?>
        <?php foreach ($_associatedProducts as $_item): ?>
        <tbody>
            <tr>
                <td data-th="<?= $block->escapeHtml(__('Product Name')) ?>" class="col item">
                    <strong class="product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
                    <?php if ($block->getCanShowProductPrice($_product)): ?>
                        <?php if ($block->getCanShowProductPrice($_item)): ?>
                            <?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>
                        <?php endif; ?>
                     <?php endif; ?>
                </td>
                 <?php 
                      $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                      $inventory = $objectManager->create('\Magento\CatalogInventory\Model\Stock\StockItemRepository');
                      $stockInventor =$inventory->get($_item->getId());
            ?>
                <?php if ($_product->isSaleable()): ?>

                <td data-th="<?= $block->escapeHtml(__('Qty')) ?>" class="col qty">
                <?php if ($stockInventor->getIsInStock()) : ?>
                    <div class="control qty">
                        <input type="number"
                               name="super_group[<?= /* @escapeNotVerified */ $_item->getId() ?>]"
                               data-selector="super_group[<?= /* @escapeNotVerified */ $_item->getId() ?>]"
                               value="<?= /* @escapeNotVerified */ $_item->getQty() * 1 ?>"
                               title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                               class="input-text qty"
                               data-validate="{'validate-grouped-qty':'#super-product-table'}"
                               data-errors-message-box="#validation-message-box"/>
                    </div>
                <?php else: ?>
                    <div class="stock unavailable" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
                        <span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
                    </div>
                <?php endif; ?>
                </td>
                <?php endif; ?>
            </tr>
           
            <?php if (!$stockInventor->getIsInStock() && $notifyBlock->isAllowCustomerGroup()) : ?>
                
            <tr>
                <td>
                    <div class="mageprakash-notify-main">
                        <div id="mageprakash-notify-form">
                            <div class="mageprakash-notify-group">
                                <div>
                                    <p><?php echo $notifyBlock->getNotificationMessage(); ?></p>
                                    <input type="hidden" id="customerId" name="customerId" value="<?php echo $notifyBlock->getLoggedCustomerId(); ?>">
                                    <input type="hidden" id="productSku" name="productSku" value="<?php echo $_item->getSku(); ?>">
                                    <input type="hidden" id="productName" name="productName" value="<?php echo $_item->getName(); ?>">
                                    <input type="hidden" name="producturl" class="producturl" value="<?php echo $_product->getUrlKey().'.html'; ?>">
                                </div>
                                <div>
                                    <div>
                                        <input type="email" id="notify" name="notify" placeholder="<?= __('Please enter your email id') ?>" value = "<?php if ($notifyBlock->isLoggedIn()) { echo trim($notifyBlock->getLoggedCustomerEmail()); } ?>">
                                    </div>
                                    <div class="mageprakash-notification" style="margin-top: 10px;">
                                        <button id="notifyGroup" class="action primary notifyGroup"  type="button" title="<?= __('Notify') ?>"><?= __('Notify') ?></button>
                                    </div>
                                </div>                                
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
            <!--  -->
            <?php endif; ?>
            <?php if ($block->getCanShowProductPrice($_product)
                && $block->getCanShowProductPrice($_item)
                && trim($block->getProductPriceHtml(
                    $_item,
                    \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                ))): ?>
                <tr class="row-tier-price">
                    <td colspan="2">
                        <?= $block->getProductPriceHtml(
                            $_item,
                            \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                        ) ?>
                    </td>
                </tr>
            <?php endif; ?>
        </tbody>
        <?php endforeach; ?>
        <?php else: ?>
        <tbody>
            <tr>
                <td class="unavailable"
                    colspan="<?php if ($_product->isSaleable()): ?>4<?php else : ?>3<?php endif; ?>">
                    <?= /* @escapeNotVerified */ __('No options of this product are available.') ?>
                </td>
            </tr>
        </tbody>
        <?php endif; ?>
    </table>
</div>
<div id="validation-message-box"></div>

<script type="text/javascript">
    require([
      'jquery',
      'jquery/ui'
    ], function($){
         $(document).ready(function() {
            $('.notifyGroup').on('click', function () {
                var body = $('body').loader();
                body.loader('show');
                var customerId = $(this).parents(".mageprakash-notify-group").find("#customerId").val();
                var productSku = $(this).parents(".mageprakash-notify-group").find("#productSku").val();
                var productName = $(this).parents(".mageprakash-notify-group").find("#productName").val();
                var customerEmail = $(this).parents(".mageprakash-notify-group").find("#notify").val();
                var producturl = $(this).parents(".mageprakash-notify-group").find(".producturl").val();
                $.ajax({
                    type: "POST",
                    url: "<?php echo $notifyBlock->getSaveUrl(); ?>",
                    data: {Id: customerId, Sku:productSku, Name:productName, Email:customerEmail, producturl:producturl},
                    success:  function(data){
                        window.location.reload(true);
                    }
                });    
            });
        });
    }); 
</script>
