<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
$om = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $om->get('\Magento\Customer\Model\SessionFactory');
$this->_customerSession = $customerSession->create();

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>

<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$notifyBlock = $block->getLayout()->createBlock('MagePrakash\OutofStockNotification\Block\Product\Notify');
$_stockHelper = $this->helper('MagePrakash\OutofStockNotification\Helper\Data');
$enableNotification = 0;

// get product lable block

?>

<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php
                    $notifyBlock->setListProduct($_product->getId());
                    $enableNotification = $_product->getIsEnableOutofstock();
                ?>
                <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                        <?= $block->getProductDetailsHtml($_product) ?>


                        <div class="product-item-inner">

                        <!-- Out of Stock Notification Start -->
                        
                        <?php if ($notifyBlock->isEnable() && $notifyBlock->isAllowCustomerGroup() == 1 && $notifyBlock->isShowNotifyOnCategory() == "1") :?>

                            <?php 
                            if (!$_product->isSaleable() && $enableNotification != 0 && $_product->getTypeId() != "configurable") :?>
                                <div class="mageprakash-notify-main">
                                    <div id="mageprakash-notify-form">
                                        <form action="#">
                                            <div>
                                                <p><?php echo $notifyBlock->getNotificationMessage(); ?></p>
                                            </div>
                                            
                                                
                                            
                                            <div class="mageprakash-stock-notification">
                                                <input type="email" class="notifyEmail" name="notify" placeholder="<?= __('Please enter your email id') ?>">
                                                <input type="hidden"  class="customerId" value="<?=$_stockHelper->getCustomerId(); ?>" />
                                                <input type="hidden"  class="productSku" value="<?=$_product->getSku(); ?>" />
                                                <input type="hidden"  class="productName" value="<?=$_product->getName(); ?>" />
                                                <input type="hidden" name="producturl" class="producturl" value="<?php echo $_product->getUrlKey().'.html'; ?>">
                                                <button class="action primary notify-button" type="button" title="<?= __('Notify') ?>" style="margin-top: 10px;"><?= __('Notify') ?></button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            <?php endif;?>
                            <?php if ($_product->getTypeId() == "configurable") :
                                $data = $_product->getTypeInstance()->getConfigurableOptions($_product);
                                $optionsData = $_product->getTypeInstance(true)->getConfigurableAttributesAsArray($_product);
                                $superAttrCode=array();
                                foreach ($optionsData as $option) {
                                    $superAttrCode[]=$option['attribute_code'];
                                }
                                $usedProducts = $_product->getTypeInstance()->getUsedProductCollection($_product);
                                foreach ($usedProducts as $childProduct) 
                                {   
                                    $stockProduct = $notifyBlock->getProductStock($childProduct->getId());
                                    $simpleProduct = $notifyBlock->getProduct($childProduct->getId());
                                   
                                    $id = "";
                                    foreach ($superAttrCode as $key => $value) {
                                            $id = $id.$simpleProduct->getData($value);
                                    }
                                    if (!$childProduct->isSaleable() && $simpleProduct->getIsEnableOutofstock() == 1 && $notifyBlock->isAllowCustomerGroup()) {
                                    ?>  
                                    <div class="mageprakash-notify-main">
                                        <div id="mageprakash-notify-form-simple">
                                            <div id= "<?php echo $id; ?>" class="mageprakash-notify-conf" style="display: none;">
                                                <div>
                                                    <p><?php echo $notifyBlock->getNotificationMessage(); ?></p>
                                                 
                                                </div>
                                                <div>
                                                    
                                                    <div>
                                                        <input type="email" class="notifyEmail" name="notify" placeholder="<?= __('Please enter your email id') ?>" value = "<?php if ($notifyBlock->isLoggedIn()) { echo trim($notifyBlock->getLoggedCustomerEmail()); } ?>">
                                                           <input type="hidden" class="customerId" name="customerId" value="<?php echo $notifyBlock->getLoggedCustomerId(); ?>">
                                                            <input type="hidden" class="productSku" name="productSku" value="<?php echo $simpleProduct->getSku(); ?>">
                                                            <input type="hidden" class="productName" name="productName" value="<?php echo $simpleProduct->getName(); ?>">
                                                            <input type="hidden" name="producturl" class="producturl" value="<?php echo $_product->getUrlKey().'.html'; ?>">
                                                        <button id="<?php echo "swatch-opt-".$_product->getId(); ?>" class="action primary notify-button" type="submit" title="<?= __('Notify') ?>"><?= __('Notify') ?></button>
                                                        <style type="text/css">
                                                            
                                                            .notify-button{ margin-top: 10px; margin-bottom:10px;}
                                                        </style>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                        <?php
                                    }
                                }
                            endif;?> 
                        <?php endif;?>


                        
                        <!-- Out of Stock Notification End -->
                        <?php if($_product->getTypeId() != 'bundle'): ?>
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart primary">
                                                <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                            
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php endif; ?>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                       class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>

<script type="text/javascript">
    require([
      'jquery',
      'jquery/ui'
    ], function($){
        $(document).ready(function() {
            $('.product-item-details').on('click', '.swatch-option', function () {
                var super_attribute = [];
                $(this).parents(".swatch-attribute").each(function() {
                    var id = jQuery(this).parents().attr('class');
                    $("."+id+" .swatch-attribute").each(function() {
                        var id = jQuery(this).attr('attribute-id');
                        console.log(id);
                        var value = jQuery(this).attr('option-selected');
                        if (value != "") 
                        {
                            super_attribute[id] = value;
                        }
                    });
                    var attr_key = Array();
                    var attr_value = Array();
                    var i = 0;
                    $.each(super_attribute, function( index, value ) {
                        if (value != undefined) {
                            attr_key[i] = index;
                            attr_value[i] = value;
                            i = i + 1;
                        }               
                    });

                    var final = "";
                    for (var i = attr_value.length - 1; i >= 0 ; i--) {
                        final = final+attr_value[i];
                    }
                    var $this = $(this).parents(".product-item-details");
                    /*console.log(($this).find(".mageprakash-notify-main"));*/

                    jQuery($this).find('.mageprakash-notify-main #mageprakash-notify-form-simple > div').each(function() {
                        var id = jQuery(this).attr('id');
                           if (id == final) 
                           {
                            jQuery($this).find('.tocart').hide();
                            $(this).css("display", "block");
                           }
                           else{
                            jQuery($this).find('.tocart').show();
                            $(this).css("display", "none");
                           }
                    });
                });
            });
            $('.notify-button').on('click', function () {
                var customerId = $(this).siblings('.customerId').val();
                var productSku = $(this).siblings('.productSku').val();
                var productName = $(this).siblings('.productName').val();
                var customerEmail = $(this).siblings('.notifyEmail').val();
                var producturl   = $(this).siblings('.producturl').val();
                $.ajax({
                    type: "POST",
                    url: "<?php echo $notifyBlock->getSaveUrl(); ?>",
                    data: {Id: customerId, Sku:productSku, Name:productName, Email:customerEmail, producturl:producturl},
                    success:  function(data){
                        window.location.reload(true);
                    }
                });    

            });
        });
    }); 
</script>
<style type="text/css">
    .mageprakash-stock-notification {
        margin: 5px;
        float: left;
    }
    .product.actions.product-item-actions {
       position: initial;
    }
</style>